export const BANKS_GLOBAL = [
  "JPMorgan Chase",
  "Bank of America",
  "Wells Fargo",
  "Citibank",
  "Capital One",
  "TD Bank",
  "PNC Bank",
  "U.S. Bank",
  "HSBC",
  "Barclays",
  "Lloyds Bank",
  "NatWest",
  "Standard Chartered",
  "Deutsche Bank",
  "BNP Paribas",
  "Société Générale",
  "Crédit Agricole",
  "Banco Santander",
  "BBVA",
  "ING",
  "UniCredit",
  "UBS",
  "MUFG Bank",
  "Mizuho Bank",
  "SMBC (Sumitomo Mitsui Banking Corporation)",
  "ICBC",
  "Bank of China",
  "China Construction Bank",
  "State Bank of India",
  "HDFC Bank",
  "ICICI Bank",
  "Axis Bank",
  "DBS Bank",
  "OCBC Bank",
  "UOB",
  "Commonwealth Bank",
  "Westpac",
  "ANZ",
  "Royal Bank of Canada",
  "Scotiabank",
];
